version: "3.7"

services:
  pinterest:
    image: ghcr.io/nexters/pinterest:${VERSION}
    ports:
      - "8080:8080"
    env_file:
      - .env
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'always'
