// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "email": "chaewonkong@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "healthcheck",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "healthcheck",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth": {
            "post": {
                "description": "Login user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "user_id, password로 로그인",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Key: 'UserLoginRequest.Password' Error:Field validation for 'Password' failed on the 'required' tag",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Anauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/films": {
            "get": {
                "description": "Find All Films",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "회원의 모든 필름 가져오기",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.Film"
                            }
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Edit Film",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "필름 수정",
                "parameters": [
                    {
                        "description": "film_id, title",
                        "name": "film",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.FilmUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Conflict: 해당 id의 film이 존재하지 않는 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Film",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "필름 생성",
                "parameters": [
                    {
                        "description": "user_id, title",
                        "name": "film",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.FilmCreationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.FilmDetailResponse"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Conflict: 해당 id의 user가 존재하지 않는 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/films/{film_id}": {
            "get": {
                "description": "Find Film by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "필름 ID로 필름 정보 가져오기",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "film_id",
                        "name": "film_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FilmDetailResponse"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Conflict: 해당 id의 film이 존재하지 않는 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Film",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "필름 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "film_id",
                        "name": "film_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Conflict: 해당 id의 film이 존재하지 않는 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/images/presigned-url": {
            "get": {
                "description": "Get Presigned URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "presigned URL 발급",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filename",
                        "name": "filename",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ImageUploadResponse"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/photo-cuts": {
            "put": {
                "description": "Edit Photo Cut",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photo_cut"
                ],
                "summary": "포토컷 수정",
                "parameters": [
                    {
                        "description": "photo_cut_id, title, text, image, link",
                        "name": "photo_cut",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PhotoCutUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Conflict: 해당 id의 photo_cut이 존재하지 않는 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Photo Cut",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photo_cut"
                ],
                "summary": "포토컷 생성",
                "parameters": [
                    {
                        "description": "title, text, link, image, film_id",
                        "name": "photo_cut",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PhotoCutCreationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.PhotoCutDetailResponse"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Conflict: 해당 id의 film이 존재하지 않는 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/photo-cuts/{photo_cut_id}": {
            "get": {
                "description": "Find Photo Cut by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photo_cut"
                ],
                "summary": "포토컷 ID로 포토컷 정보 가져오기",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "photo_cut_id",
                        "name": "photo_cut_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PhotoCutDetailResponse"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Conflict: 해당 id의 photo_cut이 존재하지 않는 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Photo Cut",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photo_cut"
                ],
                "summary": "포토컷 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "photo_cut_id",
                        "name": "photo_cut_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Conflict: 해당 id의 photo_cut이 존재하지 않는 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "put": {
                "description": "Update User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "users",
                "parameters": [
                    {
                        "description": "user_id, password, name(닉네임)",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserDetailResponse"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "users",
                "parameters": [
                    {
                        "description": "user_id, password, name(닉네임)",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserCreationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.UserCreationResponse"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict: 이미 id가 존재하는 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "description": "Find User by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserDetailResponse"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{user_id}/visit-logs": {
            "get": {
                "description": "Find all visit logs from given user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserDetailResponse"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create User's visit log",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "visit log 생성",
                        "name": "visitLog",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VisitLogCreationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.VisitLogCreationResponse"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict: 이미 id가 존재하는 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{user_id}/visit-logs/{log_id}": {
            "delete": {
                "description": "Create User's visit log",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "log_id",
                        "name": "log_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "값을 누락하고 보냈거나, 값의 타입이 잘못된 경우",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Film": {
            "type": "object",
            "properties": {
                "film_id": {
                    "type": "integer"
                },
                "likes": {
                    "type": "integer"
                },
                "order": {
                    "type": "integer"
                },
                "photo_cut_count": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.FilmCreationRequest": {
            "type": "object",
            "required": [
                "title",
                "user_id"
            ],
            "properties": {
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.FilmDetailResponse": {
            "type": "object",
            "properties": {
                "film_id": {
                    "type": "integer"
                },
                "likes": {
                    "type": "integer"
                },
                "order": {
                    "type": "integer"
                },
                "photo_cut_count": {
                    "type": "integer"
                },
                "photo_cuts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PhotoCutDetailResponse"
                    }
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.FilmUpdateRequest": {
            "type": "object",
            "required": [
                "film_id",
                "title"
            ],
            "properties": {
                "film_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.ImageUploadResponse": {
            "type": "object",
            "properties": {
                "image_url": {
                    "type": "string"
                },
                "presigned_url": {
                    "type": "string"
                }
            }
        },
        "dto.PhotoCutCreationRequest": {
            "type": "object",
            "required": [
                "film_id",
                "title"
            ],
            "properties": {
                "film_id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.PhotoCutDetailResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "film_id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "likes": {
                    "type": "integer"
                },
                "link": {
                    "type": "string"
                },
                "photo_cut_id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.PhotoCutUpdateRequest": {
            "type": "object",
            "required": [
                "photo_cut_id"
            ],
            "properties": {
                "image": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "photo_cut_id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.UserCreationRequest": {
            "type": "object",
            "required": [
                "name",
                "password",
                "user_id"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.UserCreationResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "themeColor": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                },
                "visitors": {
                    "type": "integer"
                }
            }
        },
        "dto.UserDetailResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "profile_img": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "visitors": {
                    "type": "integer"
                }
            }
        },
        "dto.UserLoginRequest": {
            "type": "object",
            "required": [
                "password",
                "user_id"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.UserUpdateRequest": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "profile_img": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "theme_color": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.VisitLogCreationRequest": {
            "type": "object",
            "required": [
                "name",
                "text",
                "user_id"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.VisitLogCreationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "log_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.grafi.cc",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "grafi API",
	Description:      "grafi API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
