basePath: /
definitions:
  dto.UserCreationRequest:
    properties:
      name:
        type: string
      password:
        type: string
      user_id:
        type: string
    required:
    - name
    - password
    - user_id
    type: object
  dto.UserCreationResponse:
    properties:
      createdAt:
        type: string
      email:
        type: string
      name:
        type: string
      text:
        type: string
      themeColor:
        type: string
      userID:
        type: string
      visitors:
        type: integer
    type: object
  dto.UserDetailResponse:
    properties:
      name:
        type: string
      profile_img:
        type: string
      text:
        type: string
      user_id:
        type: string
      visitors:
        type: integer
    type: object
  dto.UserLoginRequest:
    properties:
      password:
        type: string
      user_id:
        type: string
    required:
    - password
    - user_id
    type: object
host: https://api.grafi.cc
info:
  contact:
    email: chaewonkong@gmail.com
  description: grafi API
  title: grafi API
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: user_id, password로 로그인
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDetailResponse'
        "400":
          description: 'Key: ''UserLoginRequest.Password'' Error:Field validation
            for ''Password'' failed on the ''required'' tag'
          schema:
            type: string
        "401":
          description: Anauthorized
          schema:
            type: string
      summary: Login
      tags:
      - auth
  /get:
    get:
      consumes:
      - application/json
      description: healthcheck
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: healthcheck
      tags:
      - default
  /user:
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: user_id, password, name(닉네임)
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserCreationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserCreationResponse'
        "400":
          description: 값을 누락하고 보냈거나, 값의 타입이 잘못된 경우
          schema:
            type: string
        "409":
          description: 'Conflict: 이미 id가 존재하는 경우'
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: user
      tags:
      - user
  /user/{user_id}:
    get:
      consumes:
      - application/json
      description: Find User by ID
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDetailResponse'
        "400":
          description: 값을 누락하고 보냈거나, 값의 타입이 잘못된 경우
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: user
      tags:
      - user
swagger: "2.0"
