name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

#       -v 옵션: 빌드 과정에서 자세한 정보 출력. 각 패키지의 빌드 상태, 의존성 등 보여줌
      - name: Build
        run: |
          go build -v ./...          
      
      - name: Echo Test
        run: echo "This is test"

#       - name: Build Docker image
#         run: docker build -t grafi-go:1.0

#       - name: Push Docker image to Docker Hub
#         run: |
#           echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username YOUR_DOCKER_USERNAME --password-stdin
#           docker push your-docker-image-name
