name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Release Please
        uses: ./.github/workflows/release-please.yml

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Get Git Version
        id: version
        run: echo "::set-output name=VERSION::$(git describe --tags --abbrev=0)"

      - name: Test
        run: |
          IMAGE_TAG=${{ steps.version.outputs.VERSION }}
          echo "Image tag: $IMAGE_TAG"