name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'  # Set your desired Go version here

      - name: Get Version from Release Please
        id: get_version
        run: echo "VERSION=${{ needs.release-please.outputs.version }}" >> $GITHUB_ENV

      - name: Build Docker Image
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          echo "Building Docker image for version $VERSION ..."