name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'  # Set your desired Go version here

      - name: Get Version from Release Please
        id: get_version
        uses: actions/github-script@v4
        with:
          script: |
            const version = context.payload.workflow_run.outputs.version;
            core.setOutput('VERSION', version);

      - name: Build Docker Image
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          echo "Building Docker image for version $VERSION ..."