name: Auto Versioning with Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: release-please-action

      - name: Set Version Output
        id: set_version
        run: echo "::set-output name=version::${{ steps.release.outputs.version }}"